### ISSUE TITLE
update plugin to use newer api specs for CSI

### ISSUE THREAD

**Issue by rgevaert** [gig-tech/ovc-disk-csi-driver#3]

**Comment by chrisvdg** [comment]
CSI driver would only compile using `github.com/container-storage-interface/spec v1.0.0`.
Need to check what to add to support latest (`v1.1.0`)

**Comment by chrisvdg** [comment]
Added the required methods for the newer version of the interface.
Did not implement them as the volume expand methods don't seem to be implemented on other csi drivers projects.
I assume this is because other than the disk size increase the fs also needs to be expanded and there isn't an easy way to do that.
